# Site Configuration
[site]
  title             = "Covarrubias Customs" # Shared title for SEO and OpenGraph
  description       = "Covarrubias Customs is a U.S.-based event solutions company specializing in stage equipment rentals and event logistics. We provide everything needed to bring live events to life, including staging structures, sound systems, lighting setups, and transportation. Whether it's a small gathering or a large-scale production, Covarrubias Customs ensures a seamless experience by managing the setup, delivery, and technical logistics for all stage gear. With a commitment to reliability and versatility, we serve as a one-stop partner for event organizers who want professional-grade equipment and smooth execution." # Shared description for SEO and OpenGraph
  tagline           = "Professional Event Solutions & Stage Equipment Rentals"
  taglineSeparator = " | " # default is " - "
  baseUrl          = "https://covarrubiascustoms.netlify.app" # Base URL for the site and used in OpenGraph meta tags.
  logo              = "/images/logo.webp" # Path to the site's logo
  logoAlternate    = "/images/logoAlternate.webp" # Path to the site's logo
  logoText         = "" # Text displayed next to the logo
  logoWidth        = "100px" # Width of the logo
  logoHeight       = "70px" # Height of the logo

  # Add a trailing slash at the end of URLs (e.g., https://example.com/, https://example.com/contact/)
  # Note: Manually restart your server when you change this value
  trailingSlash = true

  # Add your site logo in image path below and open your terminal and run "npm run generate-favicons" to generate favicons for different devices and platform (https://realfavicongenerator.net/checker)
  [site.favicon]
    path  = "/images/favicons" # favicon images path (No need to change it)
    image = "/images/favicon.png" # Add your site logo path here and follow upper instruction


# SEO Metadata
# Specific SEO configurations that complement the general site settings.
# -----------------------------------------------------------------------------------------------------------------------------------
[seo]
  author   = "Covarrubias Customs"
  keywords = [
    "event equipment rental",
    "stage equipment rental",
    "event production services",
    "sound system rental",
    "lighting equipment rental",
    "staging structures",
    "event logistics",
    "live event production",
    "professional audio rental",
    "event planning services",
    "concert equipment rental",
    "festival equipment",
    "corporate event production",
    "wedding event equipment",
    "party equipment rental",
    "event management",
    "stage setup services",
    "audio visual rental",
    "event transportation",
    "Los Angeles event rental"
  ]
  robots   = "index, follow" # Instructs search engines on how to crawl and index the pages.

  [seo.robotsTxt]
    enable = true # Enables or disables robots.txt file generation on site build
    disallow = [
      "/_astro/",
      "/cdn-cgi/",
    ] # Disallow specific paths (e.g., "/_astro/", "/cdn-cgi/")

  [seo.sitemap]
    enable = true # Enables or disables sitemap generation on site build
    exclude = [] # exclude all pages that include these folder names


# Different theme settings
# -----------------------------------------------------------------------------------------------------------------------------------
[settings]
  # If you change value of any of the following three, make sure to change the folder name also from
  # - "src/content" folder
  # - "src/[...lang]/pages" folder
  # - "src/content.config.ts" collection object
  blogFolder      = "blog" # Folder where blog posts are stored
  servicesFolder  = "services" # Folder where services are stored
  portfolioFolder = "portfolio" # Folder where portfolio/projects are stored

  pagination    = 4 # Number of posts displayed on each page blog list page
  stickyHeader = true # Enables scroll-aware sticky behavior (e.g., hide on scroll down), not applicable to fixed headers
  pageHeaderDefaultImage = "/images/page-header/default.png" # if you don't pass image in frontmatter of a page then this image will be used as header image

  # docs - https://formspree.io/ | https://formsubmit.co/ | https://docs.netlify.com/forms/setup/
  # Form action URL for the contact form (For more settings related to form see "src/content/sections/contact-section.md")
  contactFormAction = "https://formsubmit.co/covarrubiascustoms@gmail.com" # Updated with the actual email
  # formspree | formsubmit.co | netlify (default is formsubmit.co)
  contactFormProvider = "formsubmit.co"

  footerDescription = "Your trusted partner for professional event solutions and stage equipment rentals. From intimate gatherings to large-scale productions, we deliver exceptional service and top-quality equipment." # Professional description for footer

  # For changing footer description and footer copyright in different languages see src/i18n/en.json and src/i18n/fr.json
  # We kindly appreciate it if you retain the theme copyright. Thank you for supporting Getastrothemes!
  [settings.copyright]
    enable = true
    text   = "Copyright © 2025 Covarrubias Customs. All rights reserved." # Updated copyright text

  # Mailchimp Subscription Form located in footer
  [settings.subscription]
    enable      = true # Enables or disable the subscription form
    title       = "Stay Updated with Our Latest Services" # Professional subscription title
    note       = "Get notified about new equipment, special offers, and industry insights." # Clear subscription note
    formAction = "https://gmail.us11.list-manage.com/subscribe/post?u=d870b06d86c16269e4b1f9b39&amp;id=12cf0c6ac2&amp;f_id=007e61e1f0"
    mailchimpTagValue = "event-services"


  # Multilingual settings (check src/config/language.json for changing the languages)
  # NOTE: Manually restart your server when you change the following multilingual table values
  [settings.multilingual]
    # Set `enable` to `true` for enabling the multilingual feature or `false` for disabling it.
    # Run `npm run remove-multilingual` for removing multilingual content files after disabling the feature.
    enable                   = false
    defaultLanguage         = "en"
    disableLanguages        = [""] # List of languages to disable (eg: ["fr", "es"])
    showDefaultLangInUrl = false # Show default language in URL (eg: https://getastrothemes.com/en/)

  # Global Contact Information
  [settings.contactInfo]
    address = "Los Angeles, <br /> CA, USA"
    email = "[covarrubiascustoms@gmail.com](mailto:covarrubiascustoms@gmail.com)"
    phone = "[+1 (000) 000-0000](tel:+10000000000)" # Update with actual phone number

  # Header Offcanvas Configuration
  # Update social links in `src/config/social.json`
  [settings.headerOffcanvas]
    enable = true
    logo = "/images/logoAlternate.webp"
    description = "Professional event solutions company specializing in stage equipment rentals, sound systems, lighting, and complete event logistics. Bringing your vision to life with reliable, high-quality equipment and seamless execution." # Updated professional description

    # Call To Action Button
    [settings.headerOffcanvas.button]
      enable = true
      label = "Get a Quote" # More action-oriented button text
      url = "/contact/"

  # Navigation Button In Header
  [settings.navigationButton]
    enable = true
    label  = "Get a Quote" # Consistent with header offcanvas
    url    = "/contact/"

  [settings.markup.tableOfContents]
    enable      = true
    expanded    = false # whether to expand the table of contents by default
    endLevel    = 5
    ordered     = false
    startLevel = 1


# OpenGraph Metadata
# Specific OpenGraph settings, using values from the [site] section where possible.
# -----------------------------------------------------------------------------------------------------------------------------------
[opengraph]
  image        = "/images/og-image.jpg" # Image used in OpenGraph previews
  ogLocale    = "en_US" # Locale setting for OpenGraph
  ogType      = "business.business" # More specific type for business
  twitter      = "@CovarrubiasCustoms" # Add Twitter handle if you have one
  twitterCard = "summary_large_image" # Type of Twitter Card to use in social sharing

# [head] (Add custom scripts, stylesheets, and meta tags to be rendered in the <head> section of the page)
# -----------------------------------------------------------------------------------------------------------------------------------
[head]
  content = """
  <meta name="geo.region" content="US-CA" />
  <meta name="geo.placename" content="Los Angeles" />
  <meta name="ICBM" content="34.0522,-118.2437" />
  <meta name="business:contact_data:locality" content="Los Angeles" />
  <meta name="business:contact_data:region" content="CA" />
  <meta name="business:contact_data:country_name" content="USA" />
  <noscript defer src="/umami.is.js" data-website-id=""></noscript>
  """
